# Generated by Django 6.0.4 on 2026-04-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=15)),
                ('date', models.DateField()),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'meal_logs',
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('user', 'meal_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entries', to='nutrition.fooditem')),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meallog')),
            ],
            options={
                'db_table': 'meal_items',
            },
        ),
    ]
