# Generated by Django 6.0.4 on 2026-04-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('category', models.CharField(choices=[('observation', 'Observation'), ('concern', 'Concern'), ('improvement', 'Improvement'), ('general', 'General')], default='general', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to='accounts.userprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notes', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notes', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'caregiver_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('bmi', 'BMI'), ('calorie_adherence', 'Calorie Adherence (%)'), ('goal_progress', 'Goal Progress (%)')], max_length=25)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_from_previous', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_logs', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'improvement_logs',
                'ordering': ['-date'],
            },
        ),
    ]
