# Generated by Django 6.0.4 on 2026-04-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('weight', 'Weight Prediction'), ('health_risk', 'Health Risk'), ('nutrition_deficit', 'Nutrition Deficit'), ('disease_progression', 'Disease Progression')], max_length=25)),
                ('time_horizon', models.CharField(help_text='e.g. "7 days", "30 days"', max_length=50)),
                ('predicted_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Percentage 0-100', max_digits=5)),
                ('description', models.TextField()),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_target', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('diet_plan', models.JSONField(default=dict, help_text='Structured daily diet plan from AI')),
                ('food_portions', models.JSONField(default=dict, help_text='Specific food portion mappings')),
                ('notes', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='health.healthrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
