import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Sparkles, RefreshCw, ChevronDown, ChevronUp } from 'lucide-react';
import { aiService } from '../../services/ai.service';
import { format, parseISO } from 'date-fns';
import Card, { CardHeader } from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Alert from '../../components/ui/Alert';
import Spinner from '../../components/ui/Spinner';

function RecommendationCard({ rec }) {
  const [expanded, setExpanded] = useState(false);
  const diet = rec.diet_plan || {};
  const portions = rec.food_portions || {};

  return (
    <Card>
      <div className="flex items-start justify-between mb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Sparkles className="h-4 w-4 text-primary-700" />
            <span className="text-xs font-medium text-primary-700 uppercase tracking-wide">AI Recommendation</span>
          </div>
          <p className="text-sm text-gray-500">{format(parseISO(rec.created_at), 'MMMM d, yyyy · h:mm a')}</p>
        </div>
        <div className="text-right">
          <p className="text-sm text-gray-500">Calorie Target</p>
          <p className="text-2xl font-bold text-primary-800">{Math.round(rec.calorie_target)}<span className="text-sm font-normal text-gray-500 ml-1">kcal/day</span></p>
        </div>
      </div>

      {rec.notes && <p className="text-sm text-gray-700 mb-4 leading-relaxed">{rec.notes}</p>}

      <button onClick={() => setExpanded(!expanded)} className="flex items-center gap-1 text-sm text-primary-800 font-medium hover:underline mb-2">
        {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        {expanded ? 'Hide' : 'View'} Full Diet Plan
      </button>

      {expanded && (
        <div className="space-y-3 border-t border-gray-100 pt-3">
          {Object.entries(diet).length > 0 && (
            <div>
              <h4 className="text-xs font-semibold text-gray-500 uppercase mb-2">Diet Plan</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {Object.entries(diet).map(([k, v]) => (
                  <div key={k} className="flex items-start gap-2 p-2 bg-gray-50 rounded-lg">
                    <span className="text-xs font-medium text-gray-600 capitalize min-w-20">{k.replace(/_/g, ' ')}:</span>
                    <span className="text-xs text-gray-700">{typeof v === 'object' ? JSON.stringify(v) : String(v)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
          {Object.entries(portions).length > 0 && (
            <div>
              <h4 className="text-xs font-semibold text-gray-500 uppercase mb-2">Recommended Food Portions</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {Object.entries(portions).map(([k, v]) => (
                  <div key={k} className="flex items-center gap-2 p-2 bg-green-50 rounded-lg">
                    <span className="text-xs font-medium text-green-800 capitalize">{k.replace(/_/g, ' ')}:</span>
                    <span className="text-xs text-green-700">{String(v)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </Card>
  );
}

export default function Recommendations() {
  const qc = useQueryClient();
  const [error, setError] = useState('');

  const { data: recs = [], isLoading } = useQuery({
    queryKey: ['recommendations'],
    queryFn: () => aiService.getRecommendations().then((r) => r.data),
  });

  const generate = useMutation({
    mutationFn: () => aiService.generateRecommendation(),
    onSuccess: () => qc.invalidateQueries(['recommendations']),
    onError: (e) => setError(e.message),
  });

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI Recommendations</h1>
          <p className="text-sm text-gray-500 mt-1">Personalized nutrition recommendations generated by our AI engine.</p>
        </div>
        <Button onClick={() => { setError(''); generate.mutate(); }} loading={generate.isPending}>
          <RefreshCw className="h-4 w-4" /> Generate New
        </Button>
      </div>

      {error && <Alert type="error" message={error} onClose={() => setError('')} />}
      {generate.isSuccess && <Alert type="success" message="New recommendation generated successfully!" />}

      <Card className="bg-primary-50 border-primary-100">
        <div className="flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-primary-700 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-primary-900">
            Recommendations are generated using your latest health record, medical conditions, nutrition goals, and recent meal data. For best results, keep your health data up to date.
          </p>
        </div>
      </Card>

      {isLoading ? (
        <div className="flex justify-center py-12"><Spinner size="lg" /></div>
      ) : recs.length === 0 ? (
        <Card className="text-center py-12">
          <Sparkles className="h-12 w-12 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500 font-medium">No recommendations yet.</p>
          <p className="text-sm text-gray-400 mb-4">Make sure you have health records logged, then generate your first recommendation.</p>
          <Button onClick={() => generate.mutate()} loading={generate.isPending}>
            <Sparkles className="h-4 w-4" /> Generate First Recommendation
          </Button>
        </Card>
      ) : (
        <div className="space-y-4">
          {recs.map((rec) => <RecommendationCard key={rec.id} rec={rec} />)}
        </div>
      )}
    </div>
  );
}
